version: '3.7'

services :
  db:
    image: postgres:10-alpine
    ports:
      - "${DB_PORT}:${DB_PORT}"
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB}"
  admin:
    image: adminer
    restart: always
    depends_on: 
      - db
    ports:
      - "${DB_ADMIN_PORT}:${DB_ADMIN_PORT}"
  minio:
      image: 'bitnami/minio:2020.11.13-debian-10-r3'
      ports:
        - 9000:9000
      environment:
        - MINIO_ACCESS_KEY=test
        - MINIO_SECRET_KEY=testtest
        - MINIO_DEFAULT_BUCKETS=mybucket